// Generated by CoffeeScript 1.8.0
var Hoek, context;

Hoek = require("hoek");

context = {};

exports.register = function(server, options, next) {
  var locals;
  locals = function(key, value) {
    return context[key] = value;
  };
  server.method({
    name: "locals",
    method: locals,
    options: {}
  });
  server.ext("onPostHandler", function(request, reply) {
    var response;
    response = request.response;
    if (response.variety === "view") {
      response.source.context = Hoek.merge(context, response.source.context || {});
    }
    return reply["continue"]();
  });
  return next();
};

exports.register.attributes = {
  pkg: require("../package.json")
};
